env:
    browser: true
    es2021: true
    jest: true

extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:@typescript-eslint/recommended
    - prettier

overrides:
    - files:
          - '*.tsx'

parser: '@typescript-eslint/parser'

parserOptions:
    ecmaVersion: latest
    sourceType: module
    ecmaFeatures:
        jsx: true

plugins:
    - react
    - react-hooks
    - '@typescript-eslint'
    - prettier

settings:
    react:
        version: 'detect'
    import/resolver:
        typescript: {}

rules:
    react/react-in-jsx-scope: off
    react/display-name: off
    camelcase: error
    spaced-comment: error
    no-duplicate-imports: error
