version: '3.1'

services:
          
  frontend:
    image: portefolio:dev 
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: frontend
    ports:
      - 3000:3000