/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { STCoinAbi } from "./STCoinAbi";
export * as factories from "./factories";
export { STCoinAbi__factory } from "./factories/STCoinAbi__factory";
